CLI-832 | Acli tool export json file with extract characters on the command acli email:configure
acquia/cli pull request #1117
Opened 2022-08-01 19:41 UTC by klaw772

**Motivation**

Fixes a bug where customers, when exporting JSON data, saw escaped forward slashes in DNS record values, causing these to not verify correctly when sent to a DNS provider.

**Proposed changes**

Adds the JSON_UNESCAPED_SLASHES constant to the json_encode() method used to dump a JSON representation of DNS record data.

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Run `./bin/acli email:configure` and verify that when exporting a JSON file, forward slashes are no longer escaped.

2022-08-02 00:05 UTC, danepowell requested changes
Thanks! Can we get an automated test to prevent this from happening again?

2022-08-02 21:27 UTC, danepowell commented
To elaborate, it looks like the createDnsText method is covered (yay!) but has zero assertions (boo!) leading to a bunch of escaped mutants:

- https://coveralls.io/builds/51325470/source?filename=src%2FCommand%2FEmail%2FConfigurePlatformEmailCommand.php#L324
- https://dashboard.stryker-mutator.io/reports/github.com/acquia/cli/main#mutant/Command/Email/ConfigurePlatformEmailCommand.php

So we _really_ need a test with a few assertions for this.

In Slack I suggested mocking the filesystem:
```
$mock_file_system = $this->mockGetFilesystem($local_machine_helper);
$mock_file_system->dumpFile($'dns-records.json', 'whatever-the-json-should-look-like')->shouldBeCalled();
```

2022-08-03 15:27 UTC, klaw772 commented on tests/phpunit/src/Commands/Email/ConfigurePlatformEmailCommandTest.php
> +  protected function mockGetFilesystem(ObjectProphecy $local_machine_helper) {
@danepowell I added this because the TestBase implementation of this method returns an actual FileSystem and not a Prophecy

2022-08-08 14:08 UTC, danepowell approved these changes

2022-08-08 14:08 UTC, merged