WIP - added prompt for php version for cs:wizard command
acquia/cli pull request #1594
Opened 2023-09-20 08:48 UTC by shubham-bansal96

**Motivation**

Fixes # GL-1836

**Proposed changes**

**Alternatives considered**

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built acli.phar](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#automatic-dev-builds) for this PR.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. (add specific steps for this pr)

2023-09-21 06:50 UTC, anavarre commented
Thanks for your contribution. Dane returns in mid-October. We'll look into finalizing and merging this then. Continue fixing tests and getting this as ready as can be in the interim!

2023-09-22 12:04 UTC, bemarlan requested changes

2023-09-22 13:02 UTC, bemarlan commented on src/Command/CodeStudio/CodeStudioCiCdVariables.php
Make same change in tests/phpunit/src/Commands/CodeStudio/CodeStudioPipelinesMigrateCommandTest.php

2023-09-28 06:07 UTC, shriacquia approved these changes

2023-09-28 16:36 UTC, bemarlan commented on tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
> +        //'--phpVersion' => $this->phpVersion,
@shubham-bansal96 Can these lines be removed instead of commented out. This option doesn't exist, so we do not need this.

2023-09-28 16:37 UTC, bemarlan commented on tests/phpunit/src/TestBase.php
> +  // protected string $phpVersion = '8.1';
This item should also be removed

2023-10-09 12:12 UTC, merged

2023-10-17 18:22 UTC, danepowell commented on src/Command/CodeStudio/CodeStudioWizardCommand.php
> +      'PHP_version_8.1' => "8.1",
Yuck. Did you pick these array keys because PHPCS was complaining or something?